- Services de remplissage de base de données à partir d'un fichier Json
mouadboufenzi/fileGenie pull request #7
Opened 2024-11-17 18:34 UTC by Morgan-sama

2024-11-18 15:43 UTC, Juknum requested changes
Ça à l'air pas mal gg

2024-11-18 15:43 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Controllers/RegisterFieldController.java
> +    @PostMapping(path = "/newFields")
```suggestion
    @PostMapping(path = "/")
```

Pas besoin de dire "newFields" si on est déjà sur l'URL `/api/file/import` et en POST

2024-11-18 15:43 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Controllers/RegisterFieldController.java
> +public class RegisterFieldController {
```suggestion
@RequestMapping("/api/file/import")
public class ImportFileController {
```

(faudrait aussi renommer le fichier `.java` dans ce cas)

2024-11-18 15:43 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Controllers/RegisterFieldController.java
> +            @RequestParam("file") MultipartFile jsonFile,
```suggestion
            @RequestParam("file") MultipartFile file,
```
Vu qu'on sait pas encore s'il s'agit d'un fichier JSON ou n'importe quoi d'autre

2024-11-18 15:43 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Controllers/RegisterFieldController.java
> +        }
```suggestion
        User user;

        try {
            user = userService.getAuthedUser(token);
        } catch (HttpException notFound) {
            return new ResponseEntity<>(notFound, notFound.getStatus());
        }
```

Tout pareil que dans `UserController`

2024-11-18 15:43 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Controllers/RegisterFieldController.java
> +        }
Ici faudrait séparer la reconnaissance du fichier (que ça soit JSON, XML, etc.) et appeler le service correspondant (que JSON pour le moment, mais prévoir avec un switch? en fonction du [type mime](https://developer.mozilla.org/en-US/docs/Web/HTTP/MIME_types) du fichier)

Un truc genre:

```java
File tmpFile = File.createTempFile("uploaded-", ".json");
file.transferTo(tmpFile);

// on recup le type mime
String mime = // TODO
// on prévoit le stockage des champs
List<Field> fields = new ArrayList<Field>();

switch (mime) {
  case "json":
  try {
    fields = jsonParserService.parseJsonToFields(tmpFile);
  } catch (Exception e) { // A voir si on peut mettre une Exception + précise
    return new ResponseEntity<>(HttpStatus.INTERNAL_SERVER_ERROR);
  }
  break;

  default:
    return new ResponseEntity<>(/* code HTTP pour un fichier non supporté? */);
}

if (/* fields à des items */) {
  registerFieldService.saveFields(fields);
}

return new ResponseEntity<>(HttpStatus.CREATED);

```

2024-11-18 15:43 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Services/UserService.java
> +            System.out.println("Voici le token de l'utilisateur : "+ session.getSessionToken());
On peut l'enlever ?

```suggestion
```

2024-11-18 21:05 UTC, Morgan-sama commented on backend/src/main/java/com/filegenie/backend/Controllers/RegisterFieldController.java
> +            @RequestParam("file") MultipartFile jsonFile,
Oui , intéressant je vais changer ça merci !

2024-11-18 21:06 UTC, Morgan-sama commented on backend/src/main/java/com/filegenie/backend/Controllers/RegisterFieldController.java
> +        }
Oui évidemment je vais ajuster le code une fois que j'aurai complètement fini avec le Json , histoire de ne pas m'embrouiller

2024-11-18 21:06 UTC, Morgan-sama commented on backend/src/main/java/com/filegenie/backend/Services/UserService.java
> +            System.out.println("Voici le token de l'utilisateur : "+ session.getSessionToken());
Oui , c'était juste pour faire mes test , à terme on va l'enlever tqt

2024-11-18 21:44 UTC, Morgan-sama commented on backend/src/main/java/com/filegenie/backend/Controllers/RegisterFieldController.java
> +        }
Juste pour tester à la base , mais j'ai oublié finalement de le retirer sinon c'est effectivement dans `UserController` qui j'ai pris ce bout de code

2024-11-18 23:09 UTC, Juknum requested changes
Plus que ça et ça devrait être gulli good mdr

2024-11-18 23:09 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Controllers/ImportFileController.java
> +        }
Du coup là faudrait que ça suive le format qu'on retrouve ailleurs: 

```suggestion
        } catch (HttpException httpError) {
                return new ResponseEntity<>(httpError, httpError.getStatus());
        }
```

2024-11-18 23:09 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Services/JsonParserService.java
> +        return processNode(null, rootNode);
Et là aussi pour que ça colle avec le controller:
```suggestion
    public List<Field> parseJsonToFields(File jsonFile) throws HttpException
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            JsonNode rootNode = objectMapper.readTree(jsonFile);
            return processNode(null, rootNode);
        } catch (Exception e) {
            throw new HttpException(HttpStatus.INTERNAL_SERVER_ERROR, "Impossible de parser le fichier JSON: " + e.getMessage());
        }
```

2024-11-19 08:16 UTC, Morgan-sama commented on backend/src/main/java/com/filegenie/backend/Controllers/ImportFileController.java
> +        }
En changeant j'ai des erreurs de syntaxes qui me disent qu'en je dois gérer les erreurs de `file.transferTo(tempFile)` et File `tempFile = File.createTempFile("uploaded-", ".json")` et en utilisant la solution proposée par l'IDE ça me rajoute deux autres `catch` sur celui que j'ai déjà , donc je vais d'abord laisser tel quel.

2024-11-19 08:39 UTC, Morgan-sama commented on backend/src/main/java/com/filegenie/backend/Services/UserService.java
Mec , j'en ai toujours besoin pour l'associer à mes requêtes postman, vu que je ne passe pas par le frontend pour faire mes tests

2024-11-19 10:00 UTC, Juknum commented on backend/src/main/java/com/filegenie/backend/Services/UserService.java
AAh merde my bad, tu peux le choper dans la base de donnée sinon

2024-11-19 11:35 UTC, Juknum commented
Si c'est tout bon je te laisse merge du coup @Morgan-sama

2024-11-19 13:43 UTC, merged